"""add Department

Revision ID: 45484fc04978
Revises: 77c319b510c2
Create Date: 2024-02-22 20:15:31.648906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45484fc04978'
down_revision = '77c319b510c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
